run:
  timeout: 3m
  issues-exit-code: 1
  tests: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# All available settings of specific linters.
linters-settings:
  funlen:
    statements: 50
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - govet
    - lll

severity:
  option: value
